<?=$this->extend('front/layouts/layouts')?>
<?=$this->section('front')?>
<?=$this->include('front/main/home/mengapapilihkami')?>
<br>
<?=$this->include('front/main/home/feature')?>
<br>
<?=$this->include('front/main/home/floorplan')?>
<br>
<?=$this->include('front/main/home/siteplan')?>
<br>
<?=$this->include('front/main/home/Hubungikami')?>
<?=$this->endSection()?>